Repository nephio-project/porch, pull requests merged in 2024-08, with the labels that each got.

#89 Sandbox debugging
  .vscode/launch.json
  Makefile
Labels: approved, lgtm

#90 Make the default value of Repository's spec.git.branch field explicit
  api/porchconfig/v1alpha1/config.porch.kpt.dev_repositories.yaml
  api/porchconfig/v1alpha1/types.go
  pkg/git/git.go
Labels: approved, lgtm

#92 fix porchсtl push method for windows
  pkg/cli/commands/rpkg/push/command.go
Labels: approved, lgtm, ok-to-test

#94 Fix minor warnings in Dockerfiles
  build/Dockerfile
  build/Dockerfile.apiserver
  build/Dockerfile.etcd
  controllers/Dockerfile
  examples/apps/hello-server/Dockerfile
  func/Dockerfile
  func/Dockerfile-wrapperserver
  test/Dockerfile
Labels: approved, lgtm

#91 Upgrade dependencies
  .github/workflows/porch-e2e.yaml
  .github/workflows/porchctl-cli-e2e.yaml
  api/go.mod
  api/go.sum
  controllers/fleetsyncs/pkg/controllers/fleetsync/controller.go
  controllers/go.mod
  controllers/go.sum
  deployments/porch/3-porch-server.yaml
  go.mod
  go.sum
  internal/kpt/util/fetch/fetch.go
  internal/kpt/util/man/man_test.go
  pkg/cmd/server/start.go
Labels: approved, lgtm

#98 Fix dev release
  .github/workflows/porch-e2e.yaml
  .github/workflows/porchctl-cli-e2e.yaml
  .github/workflows/porchctl-dev-release.yaml
Labels: approved, lgtm

#93 More sensible defaults for webhook environment variables
  deployments/porch/5-rbac.yaml
  pkg/apiserver/webhooks.go
  pkg/util/util.go
  test/e2e/suite.go
Labels: approved, lgtm

#101 Update porchctl-dev-release.yaml
  .github/workflows/porchctl-dev-release.yaml
Labels: approved

#102 Test change to porch dev build
  .github/workflows/porchctl-dev-release.yaml
Labels: approved

#95 Retry 'Update' operations that are failing due to normal optimistic locking behavior in CLI commands
  internal/kpt/util/porch/approval.go
  pkg/cli/commands/rpkg/approve/command.go
  pkg/cli/commands/rpkg/propose/command.go
  pkg/cli/commands/rpkg/propose/command_test.go
  pkg/cli/commands/rpkg/proposedelete/command.go
  pkg/cli/commands/rpkg/proposedelete/command_test.go
  pkg/cli/commands/rpkg/reject/command.go
  pkg/cli/commands/rpkg/reject/command_test.go
  pkg/cli/commands/rpkg/update/command.go
  scripts/cleanup-after-tests.sh
  test/e2e/cli/testdata/rpkg-lifecycle/config.yaml
Labels: approved, lgtm
