Repository nephio-project/porch, pull requests merged in 2024-11, with the labels that each got.

#127 Remove unused googleurl package
  pkg/googleurl/parser.go
  pkg/googleurl/parser_test.go
Labels: approved, lgtm

#119 Remove Function CRD from porchconfig and Repo
  api/porchconfig/v1alpha1/config.porch.kpt.dev_functions.yaml
  api/porchconfig/v1alpha1/config.porch.kpt.dev_repositories.yaml
  api/porchconfig/v1alpha1/groupversion_info.go
  api/porchconfig/v1alpha1/types.go
  api/porchconfig/v1alpha1/types_functions.go
  api/porchconfig/v1alpha1/zz_generated.deepcopy.go
  pkg/cache/cache.go
  pkg/cache/memory/cache.go
  pkg/cache/memory/cache_test.go
  pkg/cache/memory/repository.go
  pkg/cli/commands/repo/reg/command.go
  pkg/cli/commands/repo/reg/testdata/auth-repository.yaml
  pkg/cli/commands/repo/reg/testdata/full-repository.yaml
  pkg/cli/commands/repo/reg/testdata/simple-repository.yaml
  pkg/engine/engine.go
  pkg/oci/function.go
  pkg/oci/oci.go
  pkg/registry/porch/functions.go
  pkg/registry/porch/storage.go
  pkg/repository/repository.go
  test/e2e/cli/testdata/repo-register/config.yaml
  test/e2e/e2e_test.go
  test/e2e/suite_utils.go
Labels: approved, lgtm

#129 Fixes #812 - Porch approval takes more time with each package in the repository
  pkg/cache/memory/cache_test.go
  pkg/cache/memory/draft.go
  pkg/cache/memory/repository.go
  pkg/engine/engine.go
  pkg/engine/fake/packagerevision.go
  pkg/git/draft.go
  pkg/git/git.go
  pkg/git/git_test.go
  pkg/git/package.go
  pkg/oci/mutate.go
  pkg/oci/oci.go
  pkg/registry/porch/packagecommon.go
  pkg/repository/repository.go
Labels: approved, lgtm

#130 Remove Function api resource
  api/generated/clientset/versioned/typed/porch/v1alpha1/fake/fake_function.go
  api/generated/clientset/versioned/typed/porch/v1alpha1/fake/fake_porch_client.go
  api/generated/clientset/versioned/typed/porch/v1alpha1/function.go
  api/generated/clientset/versioned/typed/porch/v1alpha1/generated_expansion.go
  api/generated/clientset/versioned/typed/porch/v1alpha1/porch_client.go
  api/generated/informers/externalversions/generic.go
  api/generated/informers/externalversions/porch/v1alpha1/function.go
  api/generated/informers/externalversions/porch/v1alpha1/interface.go
  api/generated/listers/porch/v1alpha1/expansion_generated.go
  api/generated/listers/porch/v1alpha1/function.go
  api/generated/openapi/zz_generated.openapi.go
  api/porch/register.go
  api/porch/types.go
  api/porch/v1alpha1/register.go
  api/porch/v1alpha1/types.go
  api/porch/v1alpha1/zz_generated.conversion.go
  api/porch/v1alpha1/zz_generated.deepcopy.go
  api/porch/zz_generated.deepcopy.go
  examples/config/function-repository.yaml
  internal/kpt/util/cmdutil/cmdutil.go
  internal/kpt/util/cmdutil/cmdutil_test.go
  internal/kpt/util/function/catalogfn.go
  internal/kpt/util/function/matcher.go
  internal/kpt/util/porch/function.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/resolvetoimage.go
Labels: approved, lgtm

#123 Fix overwrite of package resources with empty resource map
  pkg/engine/engine.go
  test/e2e/e2e_test.go
Labels: bug, approved, lgtm

#126 Adding Porch private authenticated registries functionality
  deployments/porch/5-rbac.yaml
  func/internal/podevaluator.go
  func/internal/podevaluator_podmanager_test.go
  func/server/server.go
Labels: approved, lgtm

#80 Porchctl repo command fixes
  pkg/cli/commands/repo/get/command.go
  pkg/cli/commands/repo/reg/command.go
  pkg/cli/commands/repo/unreg/command.go
Labels: approved, lgtm, ok-to-test

#132 Automatically trigger the "release" Github action by pushing pre-release tags
  .github/workflows/release.yaml
Labels: approved, lgtm

#138 Implement improvements identified by static linting
  pkg/engine/clone.go
  pkg/engine/clone_test.go
  pkg/engine/engine.go
  pkg/engine/mergekey.go
  pkg/engine/patchgen.go
  pkg/engine/update.go
Labels: approved, lgtm

#137 Move functions
  pkg/engine/engine.go
  pkg/engine/update.go
Labels: approved, lgtm

#136 Fix two warnings in repository.go
  pkg/cache/memory/repository.go
Labels: approved, lgtm

#134 Fix hardcoded background job periodic poll interval
  Makefile
  cmd/porchctl/run/run.go
  deployments/porch/3-porch-server.yaml
  pkg/apiserver/apiserver.go
  pkg/cmd/server/start.go
  pkg/cmd/server/start_test.go
  pkg/registry/porch/background.go
Labels: approved, lgtm

#131 Tag container images built from git commits tagged with vX.Y.Z with the same vX.Y.Z tag
  .github/workflows/dev-image-build.yaml
Labels: approved, lgtm

#133 Add a porch blueprint (kpt package) to GitHub Release assets
  .github/workflows/release.yaml
  release/tag/goreleaser.yaml
Labels: approved, lgtm

#142 Fix rendering big (>4MB) packages with function-runner
  .vscode/launch.json
  Makefile
  deployments/porch/2-function-runner.yaml
  deployments/porch/3-porch-server.yaml
  func/internal/executableevaluator.go
  func/internal/podevaluator.go
  func/internal/podevaluator_podmanager_test.go
  func/server/server.go
  func/wrapper-server/main.go
  pkg/apiserver/apiserver.go
  pkg/cmd/server/start.go
  pkg/engine/clone_test.go
  pkg/engine/grpcruntime.go
  pkg/engine/options.go
  test/e2e/e2e_test.go
Labels: approved, lgtm

#143 Fix "release" GitHub Action
  .github/workflows/release.yaml
Labels: approved

#141 Script to run a Porch load test
  scripts/run-load-test.sh
Labels: approved, lgtm

#144 Rename interface PackageDraft to PackageRevisionDraft
  pkg/cache/memory/draft.go
  pkg/cache/memory/repository.go
  pkg/git/draft.go
  pkg/git/git.go
  pkg/oci/mutate.go
  pkg/repository/fake/repository.go
  pkg/repository/repository.go
  pkg/task/generictaskhandler.go
  pkg/task/taskhandler.go
Labels: approved, lgtm
