Repository nephio-project/porch, pull requests merged in 2024-06, with the labels that each got.

#57 Make end-to-end tests work with a local porch-server
  .gitignore
  .vscode/launch.json
  Makefile
  build/Dockerfile.apiserver
  pkg/apiserver/apiserver.go
  pkg/apiserver/webhooks.go
  pkg/apiserver/webhooks_test.go
  pkg/cmd/server/start.go
  scripts/clean-kind-only-e2e-test.sh
  scripts/create-deployment-kpt.sh
  test/e2e/cli/cli_test.go
  test/e2e/cli/cluster.go
  test/e2e/cli/config.go
  test/e2e/cli/testdata/git-server.yaml
  test/e2e/cli/testdata/rpkg-init/config.yaml
  test/e2e/e2e_test.go
  test/e2e/e2e_test_utils.go
  test/e2e/suite.go
Labels: approved, lgtm

#62 Add warning about using WSL2 and fix lint errors
  docs/tutorials/porch-development-environment/README.md
Labels: approved, lgtm, ok-to-test

#54 Pod templating for function runner
  docs/09-function-runner-pod-templates.md
  func/internal/podevaluator.go
  func/internal/podevaluator_podmanager_test.go
  func/server/server.go
  pkg/util/util.go
Labels: approved, lgtm, ok-to-test

#64 Fix KUBECONFIG var for clean_e2e runs
  scripts/clean-kind-only-e2e-test.sh
Labels: approved, lgtm

#53 Allow configuration of an external webhook & associated certs
  pkg/apiserver/webhooks.go
  pkg/apiserver/webhooks_test.go
Labels: approved, lgtm

#66 Minor improvements to end-to-end testing framework
  scripts/clean-kind-only-e2e-test.sh
  test/e2e/e2e_test.go
  test/e2e/e2e_utils_test.go
  test/e2e/suite.go
  test/e2e/suite_logs.go
Labels: enhancement, approved, lgtm

#65 #735 - Fix porchctl version by injecting release version into run.go module
  release/tag/goreleaser.yaml
Labels: approved, lgtm

#69 Adding porch image builds for every PR merged tagged latest
  .prow.yaml
Labels: approved, lgtm

#67 Use local porch pkg build for e2e tests
  .github/workflows/porch-e2e.yaml
  .github/workflows/porchctl-cli-e2e.yaml
  Makefile
  deployments/porch/1-namespace.yaml
  deployments/porch/2-function-runner.yaml
  deployments/porch/3-porch-server.yaml
  deployments/porch/4-apiservice.yaml
  deployments/porch/5-rbac.yaml
  deployments/porch/6-rbac-bind.yaml
  deployments/porch/7-auth-reader.yaml
  deployments/porch/8-auth-delegator.yaml
  deployments/porch/9-controllers.yaml
  docs/running-porch-in-kind-cluster.md
  docs/tutorials/porch-development-environment/bin/setup.sh
  go.mod
  scripts/clean-kind-only-e2e-test.sh
  scripts/create-deployment-blueprint.sh
Labels: approved, lgtm

#68 Fix caching in case multiple Repository resources point to the same git repo
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/registry/porch/background.go
  pkg/registry/porch/packagecommon.go
  scripts/create-deployment-blueprint.sh
  test/e2e/e2e_test.go
Labels: approved, lgtm

#71 Excluding changes in Prow files from triggering e2e runs
  .github/workflows/porch-e2e.yaml
  .github/workflows/porchctl-cli-e2e.yaml
Labels: approved, lgtm

#72 Improvements in the development process
  .github/workflows/porch-e2e.yaml
  .github/workflows/porchctl-cli-e2e.yaml
  .vscode/launch.json
  Makefile
  build/Dockerfile
  controllers/Dockerfile
  controllers/Makefile
  deployments/local/kind_porch_test_cluster.yaml
  deployments/local/metallb-conf.yaml
  deployments/local/replace-gitea-service-ports.yaml
  docs/tutorials/porch-development-environment/README.md
  docs/tutorials/porch-development-environment/bin/setup.sh
  docs/tutorials/porch-development-environment/dev-process.md
  func/Dockerfile
  func/Dockerfile-wrapperserver
  func/Makefile
  scripts/clean-e2e-test.sh
  scripts/cleanup-after-tests.sh
  scripts/remove-controller-from-deployment-config.sh
  scripts/remove-porch-server-from-deployment-config.sh
  scripts/setup-dev-env.sh
  test/Dockerfile
  test/Makefile
Labels: approved, lgtm

#73 Yet another improvement to development process
  .prow.yaml
  .vscode/launch.json
  Makefile
Labels: approved, lgtm

#74 Ignore ARM architecture warning on e2e test results
  test/e2e/cli/cli_test.go
Labels: approved, lgtm

#61 Make PackageRevision's metadata.uid field unique
  pkg/git/package.go
  test/e2e/cli/testdata/rpkg-clone/config.yaml
  test/e2e/cli/testdata/rpkg-copy/config.yaml
  test/e2e/cli/testdata/rpkg-init-deploy/config.yaml
  test/e2e/cli/testdata/rpkg-init/config.yaml
  test/e2e/cli/testdata/rpkg-push/config.yaml
  test/e2e/e2e_test.go
Labels: bug, approved, lgtm

#77 Porchctl dev release workflow
  .github/workflows/porchctl-dev-release.yaml
Labels: approved, lgtm

#78 Adding tgz creation step
  .github/workflows/porchctl-dev-release.yaml
Labels: approved, lgtm

#70 Add support for new field selectors: spec.workspaceName and spec.lifecycle
  pkg/registry/porch/fieldselector.go
  pkg/repository/repository.go
  test/e2e/e2e_test.go
Labels: approved, lgtm

#76 PackageVariant controller: Use the default exponential back-off in case of errors, instead of a constant 30 sec retry
  controllers/packagevariants/pkg/controllers/packagevariant/packagevariant_controller.go
Labels: approved, lgtm

#79 Fix the porchctl build to run on Ubuntu 20.04
  .github/workflows/porchctl-dev-release.yaml
Labels: approved, lgtm
