Repository nephio-project/porch, pull requests merged in 2025-03, with the labels that each got.

#166 adding livenessProbe and readinessProbe in deployment.yaml for porch …
  deployments/porch/3-porch-server.yaml
  deployments/porch/9-controllers.yaml
Labels: approved, lgtm

#191 Add sonar props file
  .vscode/settings.json
  sonar-project.properties
Labels: approved, lgtm

#189 add missing license headers
  api/Makefile
  func/evaluator/evaluator_grpc.pb.go
  func/internal/podevaluator_podmanager_test.go
  pkg/externalrepo/git/mainbranchstrategy_string.go
  pkg/kpt/fn/third_party/GoogleContainerTools/kpt-functions-catalog/functions/go/apply_replacements/replacements.go
  pkg/kpt/fn/third_party/GoogleContainerTools/kpt-functions-catalog/functions/go/applysetters/apply_setters.go
  pkg/kpt/fn/third_party/GoogleContainerTools/kpt-functions-catalog/functions/go/applysetters/walk.go
  pkg/kpt/fn/third_party/GoogleContainerTools/kpt-functions-catalog/functions/go/set_namespace/utils.go
  pkg/kpt/fn/third_party/GoogleContainerTools/kpt-functions-catalog/functions/go/starlark/generated/docs.go
  pkg/kpt/fn/third_party/GoogleContainerTools/kpt-functions-catalog/functions/go/starlark/krmfn/krmfn.go
  pkg/kpt/fn/third_party/GoogleContainerTools/kpt-functions-catalog/functions/go/starlark/starlark/config.go
  pkg/kpt/fn/third_party/GoogleContainerTools/kpt-functions-catalog/functions/go/starlark/starlark/config_test.go
  pkg/kpt/fn/third_party/GoogleContainerTools/kpt-functions-catalog/functions/go/starlark/starlark/processor.go
  pkg/kpt/fn/third_party/GoogleContainerTools/kpt-functions-catalog/functions/go/starlark/third_party/sigs.k8s.io/kustomize/kyaml/fn/runtime/starlark/context.go
  pkg/kpt/fn/third_party/GoogleContainerTools/kpt-functions-catalog/functions/go/starlark/third_party/sigs.k8s.io/kustomize/kyaml/fn/runtime/starlark/doc.go
  pkg/kpt/fn/third_party/GoogleContainerTools/kpt-functions-catalog/functions/go/starlark/third_party/sigs.k8s.io/kustomize/kyaml/fn/runtime/starlark/loadlib.go
  pkg/kpt/fn/third_party/GoogleContainerTools/kpt-functions-catalog/functions/go/starlark/third_party/sigs.k8s.io/kustomize/kyaml/fn/runtime/starlark/starlark.go
  scripts/cleanup-after-tests.sh
  scripts/generate-api.sh
  scripts/run-load-test.sh
Labels: approved, lgtm, ok-to-test

#187 Add OSSF badges
  README.md
Labels: approved, lgtm

#195 Skip Duplicate line check for unit-tests
  sonar-project.properties
Labels: approved, lgtm

#197 Add properties file for automatic analysis
  .sonarcloud.properties
Labels: approved, lgtm

#198 fixed custom registry imagePullSecret override
  func/internal/podevaluator.go
Labels: approved, lgtm

#201 Move shebang before copyright notices in scripts
  scripts/cleanup-after-tests.sh
  scripts/generate-api.sh
  scripts/run-load-test.sh
Labels: approved, lgtm

#190 Implement human readable PackageRevision IDs
  deployments/local/makekeys.sh
  pkg/engine/engine.go
  pkg/externalrepo/git/git.go
  pkg/externalrepo/git/package.go
  pkg/externalrepo/oci/mutate.go
  pkg/registry/porch/background.go
  pkg/registry/porch/packagecommon.go
  pkg/registry/porch/packagerevisionresources.go
  pkg/registry/porch/strategy.go
  pkg/repository/package.go
  pkg/repository/util.go
  pkg/repository/util_test.go
  pkg/task/edit_test.go
  pkg/util/testdata/pkg-rev-name.yaml
  pkg/util/util.go
  pkg/util/util_test.go
  test/e2e/cli/testdata/rpkg-clone/config.yaml
  test/e2e/cli/testdata/rpkg-copy/config.yaml
  test/e2e/cli/testdata/rpkg-get/config.yaml
  test/e2e/cli/testdata/rpkg-init-deploy/config.yaml
  test/e2e/cli/testdata/rpkg-init/config.yaml
  test/e2e/cli/testdata/rpkg-lifecycle/config.yaml
  test/e2e/cli/testdata/rpkg-push/config.yaml
  test/e2e/cli/testdata/rpkg-unready/config.yaml
  test/e2e/cli/testdata/rpkg-update/config.yaml
  test/e2e/e2e_test.go
  test/e2e/update_test.go
Labels: approved, lgtm

#188 Create sonarcloud.yml
  .github/workflows/sonarcloud.yml
Labels: approved

#204 Fix coverage report for sonar
  default-go-test.mk
Labels: approved, lgtm

#205 Add workflow to archive coverage data
  .github/workflows/sonar-ci-artifacts.yaml
  .github/workflows/sonarcloud.yml
Labels: approved

#206 Clean up sonar workflow yaml
  .github/workflows/sonarcloud.yml
Labels: approved, lgtm

#211 Adding check for docker desktop
  scripts/remove-porch-server-from-deployment-config.sh
Labels: approved, lgtm

#193 Make commit author and email customisable for git repositories
  api/porchconfig/v1alpha1/config.porch.kpt.dev_repositories.yaml
  api/porchconfig/v1alpha1/types.go
  controllers/config/crd/bases/config.porch.kpt.dev_packagevariants.yaml
  controllers/config/crd/bases/config.porch.kpt.dev_packagevariantsets.yaml
  controllers/config/rbac/role.yaml
  controllers/packagevariants/api/v1alpha1/zz_generated.deepcopy.go
  controllers/packagevariants/config/rbac/role.yaml
  controllers/packagevariantsets/api/v1alpha1/zz_generated.deepcopy.go
  controllers/packagevariantsets/api/v1alpha2/zz_generated.deepcopy.go
  controllers/packagevariantsets/config/rbac/role.yaml
  pkg/externalrepo/git/git.go
  pkg/externalrepo/git/git_test.go
  pkg/kpt/api/kptfile/v1/zz_generated.deepcopy.go
Labels: approved, lgtm

#202 Handle invalid kpt annotations more gracefully, handle tags with messages
  api/porch/v1alpha1/types.go
  api/porch/v1alpha1/zz_generated.conversion.go
  controllers/packagevariants/pkg/controllers/packagevariant/packagevariant_controller.go
  go.mod
  pkg/cache/crcache/repository.go
  pkg/cli/commands/rpkg/clone/command.go
  pkg/cli/commands/rpkg/copy/command.go
  pkg/cli/commands/rpkg/init/command.go
  pkg/errors/errors.go
  pkg/externalrepo/git/annotation.go
  pkg/externalrepo/git/draft.go
  pkg/externalrepo/git/git.go
  pkg/externalrepo/git/git_test.go
  pkg/externalrepo/git/package.go
  pkg/externalrepo/git/package_test.go
  pkg/externalrepo/git/package_tree.go
  pkg/externalrepo/git/ref.go
  pkg/externalrepo/git/testdata/.gitignore
  pkg/externalrepo/git/testdata/manual-tagged-repository.tar
  pkg/externalrepo/git/testdata/manually-tagged-repository.md
  pkg/externalrepo/git/testdata/nested-repository-with-invalid-kpt-annotation.md
  pkg/externalrepo/git/testdata/nested-repository-with-invalid-kpt-annotation.tar
  pkg/externalrepo/oci/mutate.go
  pkg/externalrepo/oci/oci.go
  pkg/registry/porch/fieldselector.go
  pkg/registry/porch/packagecommon.go
  pkg/repository/repository.go
  pkg/task/clone.go
  pkg/task/clone_test.go
  pkg/util/util.go
  test/e2e/e2e_test.go
  test/e2e/suite_utils.go
Labels: approved, lgtm

#207 Port main E2E test suite to testify
  .github/workflows/golangci-lint.yaml
  default-go-lint.mk
  test/e2e/e2e_test.go
  test/e2e/suite.go
  test/e2e/suite_logs.go
  test/e2e/suite_utils.go
  test/e2e/update_test.go
  test/ociserver/pkg/oci/responses.go
Labels: approved, lgtm

#192 Git Token Based Authentication
  pkg/apiserver/apiserver.go
  pkg/registry/porch/secret.go
  pkg/registry/porch/secret_test.go
Labels: approved, lgtm

#209 New Copy-Merge update strategy
  api/porch/types.go
  api/porch/v1alpha1/types.go
  internal/kpt/util/update/copy-merge.go
  internal/kpt/util/update/copy-merge_test.go
  internal/kpt/util/update/update.go
  pkg/cli/commands/rpkg/clone/command.go
  pkg/cli/commands/rpkg/clone/command_test.go
  pkg/cli/commands/rpkg/docs/docs.go
  pkg/cli/commands/rpkg/update/command.go
  pkg/kpt/api/kptfile/v1/types.go
  pkg/repository/update.go
  pkg/repository/update_test.go
  pkg/task/update.go
  pkg/task/update_test.go
  sonar-project.properties
Labels: approved, lgtm

#217 Fix object names for upstream and placeholder packages
  pkg/cache/crcache/cache_test.go
  pkg/externalrepo/git/git.go
  pkg/externalrepo/git/package.go
  pkg/repository/util.go
  pkg/repository/util_test.go
  test/e2e/cli/testdata/rpkg-update/config.yaml
Labels: approved, lgtm
