Repository nephio-project/porch, pull requests merged in 2025-05, with the labels that each got.

#241 Add flag to disable fn pods deployed at startup
  func/internal/podevaluator.go
  func/server/server.go
Labels: enhancement, approved, lgtm

#244 Skip patch mutation for Copy-Merge
  pkg/task/generictaskhandler.go
  pkg/task/generictaskhandler_test.go
  pkg/task/patchgen.go
  pkg/task/patchgen_test.go
Labels: approved, lgtm

#239 Add e2e tests for repository-synchronisation background job
  .vscode/launch.json
  test/e2e/e2e_test.go
  test/e2e/suite_utils.go
Labels: approved, lgtm

#243 Fix double polling of repositories at sync startup
  pkg/cache/crcache/repository.go
Labels: approved, lgtm

#249 Update PVS to allow WorkspaceName on Upstream PR references
  controllers/packagevariantsets/pkg/controllers/packagevariantset/packagevariantset_controller.go
  controllers/packagevariantsets/pkg/controllers/packagevariantset/packagevariantset_controller_test.go
  controllers/packagevariantsets/pkg/controllers/packagevariantset/validate.go
  controllers/packagevariantsets/pkg/controllers/packagevariantset/validate_test.go
Labels: bug, approved, lgtm

#240 Migrate cli e2e suite to use real gitea
  .github/workflows/porchctl-cli-e2e.yaml
  .vscode/launch.json
  Makefile
  deployments/local/kind_porch_test_cluster.yaml
  deployments/local/replace-gitea-service-ports.yaml
  scripts/clean-e2e-test.sh
  scripts/install-dev-gitea-setup.sh
  scripts/setup-dev-env.sh
  test/e2e/cli/cluster.go
  test/e2e/cli/suite.go
  test/e2e/cli/testdata/git-server.yaml
  test/e2e/cli/testdata/repo-register/config.yaml
  test/e2e/cli/testdata/rpkg-clone/config.yaml
  test/e2e/cli/testdata/rpkg-copy/config.yaml
  test/e2e/cli/testdata/rpkg-get/config.yaml
  test/e2e/cli/testdata/rpkg-init-deploy/config.yaml
  test/e2e/cli/testdata/rpkg-init/config.yaml
  test/e2e/cli/testdata/rpkg-lifecycle/config.yaml
  test/e2e/cli/testdata/rpkg-push/config.yaml
  test/e2e/cli/testdata/rpkg-unready/config.yaml
  test/e2e/cli/testdata/rpkg-update-alt/config.yaml
  test/e2e/cli/testdata/rpkg-update/config.yaml
  test/pkgs/gitea-dev/deployment.yaml
  test/pkgs/gitea-dev/gitea-config.yaml
  test/pkgs/gitea-dev/gitea-init.yaml
  test/pkgs/gitea-dev/namespace.yaml
  test/pkgs/gitea-dev/secret-git-user.yaml
  test/pkgs/gitea-dev/service-lb.yaml
  test/pkgs/gitea-dev/service.yaml
  test/pkgs/test-pkgs/test-blueprints.bundle
  test/pkgs/unready/Kptfile
  test/pkgs/unready/README.md
  test/pkgs/unready/namespace.yaml
Labels: enhancement, approved, lgtm

#251 Correctly parse ResultList.Results as both slice and map
  third_party/GoogleContainerTools/kpt-functions-sdk/go/fn/internal/map.go
  third_party/GoogleContainerTools/kpt-functions-sdk/go/fn/internal/maphelpers.go
  third_party/GoogleContainerTools/kpt-functions-sdk/go/fn/internal/scalar.go
  third_party/GoogleContainerTools/kpt-functions-sdk/go/fn/internal/slice.go
  third_party/GoogleContainerTools/kpt-functions-sdk/go/fn/internal/variant.go
  third_party/GoogleContainerTools/kpt-functions-sdk/go/fn/object_test.go
  third_party/GoogleContainerTools/kpt-functions-sdk/go/fn/resourcelist.go
Labels: approved, lgtm

#250 Update Kpt File before replacing the files for `copy-merge`
  internal/kpt/util/update/copy-merge.go
  internal/kpt/util/update/copy-merge_test.go
Labels: approved, lgtm

#233 fix for #834 adding logic to make porch API calls atomic
  pkg/engine/engine.go
  pkg/engine/engine_test.go
  test/e2e/e2e_test.go
Labels: approved, lgtm

#253 Use absolute rather than relative path in the local test gitea install script
  scripts/install-dev-gitea-setup.sh
Labels: bug, approved, lgtm

#236 Upgrade Go version, base images, and dependencies flagged by Anchor Scan
  .github/workflows/golangci-lint.yaml
  .github/workflows/gosec-scan.yaml
  .github/workflows/porch-e2e.yaml
  .github/workflows/porchctl-cli-e2e.yaml
  .github/workflows/porchctl-dev-release.yaml
  .github/workflows/release.yaml
  .github/workflows/sonar-ci-artifacts.yaml
  .prow.yaml
  build/Dockerfile
  controllers/Dockerfile
  default-go-test.mk
  default-gosec.mk
  examples/apps/hello-server/Dockerfile
  func/Dockerfile
  func/Dockerfile-wrapperserver
  go.mod
  go.sum
  test/Dockerfile
Labels: approved, lgtm, ok-to-test

#257 Improve function runner logging
  func/healthchecker/healthchecker.go
  internal/kpt/fnruntime/runner.go
Labels: approved, lgtm

#245 Align rpkg push with kubectl
  pkg/cli/commands/rpkg/docs/docs.go
  pkg/cli/commands/rpkg/push/command.go
  test/e2e/cli/testdata/rpkg-push/config.yaml
Labels: approved, lgtm

#255 Fix watch namespace filter
  pkg/registry/porch/packagecommon.go
  pkg/registry/porch/packagecommon_test.go
Labels: approved, lgtm
