Repository nephio-project/porch, pull requests merged in 2025-02, with the labels that each got.

#176 Bump go versions to 1.23.5
  .prow.yaml
  build/Dockerfile
  build/Dockerfile.apiserver
  build/Dockerfile.etcd
  controllers/Dockerfile
  default-go-lint.mk
  default-go-test.mk
  examples/apps/hello-server/Dockerfile
  func/Dockerfile
  func/Dockerfile-wrapperserver
  go.mod
  scripts/boilerplate.go.txt
  scripts/boilerplate.yaml.txt
  scripts/setup-dev-env.sh
  test/Dockerfile
Labels: approved, lgtm

#177 Use full resource paths in porchctl repo/rpkg get
  pkg/cli/commands/repo/get/command.go
  pkg/cli/commands/rpkg/get/command.go
Labels: approved, lgtm

#182 changed mutex in cache repository to read write mutex so that all concurrent reads are allowed
  pkg/cache/memory/repository.go
Labels: approved, lgtm

#178 Add additional info to error when blockOwnerDeletion is enabled
  pkg/engine/engine.go
  pkg/repository/util.go
Labels: approved, lgtm

#185 Add OpenSSF scorecard gh action
  .github/workflows/openssf_scorecard.yaml
Labels: enhancement, approved, lgtm

#181 adding e2e test validation for PR #167 Modify event on the porch Repo Custom Resource
  test/e2e/e2e_test.go
Labels: approved, lgtm

#186 Add SECURITY.md
  SECURITY.md
Labels: approved, lgtm

#179 Removed upstream, mutators and validators from Repository API specification
  api/porchconfig/v1alpha1/config.porch.kpt.dev_repositories.yaml
  api/porchconfig/v1alpha1/types.go
  api/porchconfig/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, ok-to-test

#183 Some documentation and a testcase on the behavior of kpt.dev/latest-revision label
  api/generated/clientset/versioned/clientset.go
  api/generated/clientset/versioned/fake/clientset_generated.go
  api/generated/clientset/versioned/fake/doc.go
  api/generated/clientset/versioned/fake/register.go
  api/generated/clientset/versioned/scheme/doc.go
  api/generated/clientset/versioned/scheme/register.go
  api/generated/clientset/versioned/typed/porch/v1alpha1/doc.go
  api/generated/clientset/versioned/typed/porch/v1alpha1/fake/doc.go
  api/generated/clientset/versioned/typed/porch/v1alpha1/fake/fake_packagerevision.go
  api/generated/clientset/versioned/typed/porch/v1alpha1/fake/fake_packagerevisionresources.go
  api/generated/clientset/versioned/typed/porch/v1alpha1/fake/fake_porch_client.go
  api/generated/clientset/versioned/typed/porch/v1alpha1/fake/fake_porchpackage.go
  api/generated/clientset/versioned/typed/porch/v1alpha1/generated_expansion.go
  api/generated/clientset/versioned/typed/porch/v1alpha1/packagerevision.go
  api/generated/clientset/versioned/typed/porch/v1alpha1/packagerevisionresources.go
  api/generated/clientset/versioned/typed/porch/v1alpha1/porch_client.go
  api/generated/clientset/versioned/typed/porch/v1alpha1/porchpackage.go
  api/generated/informers/externalversions/factory.go
  api/generated/informers/externalversions/generic.go
  api/generated/informers/externalversions/internalinterfaces/factory_interfaces.go
  api/generated/informers/externalversions/porch/interface.go
  api/generated/informers/externalversions/porch/v1alpha1/interface.go
  api/generated/informers/externalversions/porch/v1alpha1/packagerevision.go
  api/generated/informers/externalversions/porch/v1alpha1/packagerevisionresources.go
  api/generated/informers/externalversions/porch/v1alpha1/porchpackage.go
  api/generated/listers/porch/v1alpha1/expansion_generated.go
  api/generated/listers/porch/v1alpha1/packagerevision.go
  api/generated/listers/porch/v1alpha1/packagerevisionresources.go
  api/generated/listers/porch/v1alpha1/porchpackage.go
  api/generated/openapi/zz_generated.openapi.go
  api/porch/types.go
  api/porch/v1alpha1/types.go
  api/porch/v1alpha1/zz_generated.conversion.go
  api/porch/v1alpha1/zz_generated.deepcopy.go
  api/porch/v1alpha1/zz_generated.defaults.go
  api/porch/zz_generated.deepcopy.go
  test/e2e/e2e_test.go
  test/e2e/suite_utils.go
Labels: approved, lgtm

#184 Address gosec errors
  default-gosec.mk
  deployments/local/makekeys.sh
  func/internal/podevaluator.go
  internal/kpt/fnruntime/nodejs.go
  internal/kpt/fnruntime/wasm.go
  internal/kpt/fnruntime/wasmtime.go
  internal/kpt/util/cmdutil/cmdutil.go
  pkg/apiserver/webhooks.go
  pkg/cli/commands/rpkg/pull/command.go
  pkg/externalrepo/git/testing_repo.go
  pkg/registry/porch/wi/wi.go
  pkg/repository/testing.go
  pkg/repository/update.go
Labels: approved, lgtm
