Repository nephio-project/porch, pull requests merged in 2025-09, with the labels that each got.

#313 Fix missing Tasks List in db-cache, update wrapper-server and render logs
  func/wrapper-server/main.go
  internal/kpt/util/render/executor.go
  pkg/engine/pushpr.go
Labels: approved, lgtm

#318 Split dev & prod docker build-push actions
  .github/workflows/image-build-push-dev.yaml
  .github/workflows/image-build-push-release.yaml
Labels: approved, lgtm, gh action

#320 Porchctl: Upgrade fallback when there is no original edit task
  pkg/cli/commands/rpkg/upgrade/command.go
  pkg/cli/commands/rpkg/upgrade/command_test.go
Labels: approved, lgtm

#322 Postgres image update to new Bitnami repository
  deployments/local/postgres/postgres-statefulset.yaml
Labels: bug, approved, lgtm

#321 Rewrite DB cache tests to use testify test suite
  pkg/cache/dbcache/dbcache_test.go
  pkg/cache/dbcache/dbpackagerevision_test.go
  pkg/cache/dbcache/dbpackagerevisionsql_test.go
  pkg/cache/dbcache/dbpackagesql_test.go
  pkg/cache/dbcache/dbrepository_test.go
  pkg/cache/dbcache/dbrepositorysql_test.go
  pkg/cache/dbcache/dbreposync_test.go
  pkg/cache/dbcache/dbsql_test.go
  pkg/cache/dbcache/util_test.go
Labels: approved, lgtm

#324 Fix porch release gh actions
  .github/workflows/porchctl-dev-release.yaml
  .github/workflows/release.yaml
Labels: bug, approved, lgtm, gh action

#327 Update mockery to v3
  .mockery.yaml
  .mockery.yaml.bak
  default-mockery.mk
  test/mockery/mocks/external/sigs.k8s.io/controller-runtime/pkg/client/mock_Client.go
  test/mockery/mocks/external/sigs.k8s.io/controller-runtime/pkg/client/mock_Reader.go
  test/mockery/mocks/external/sigs.k8s.io/controller-runtime/pkg/client/mock_SubResourceWriter.go
  test/mockery/mocks/external/sigs.k8s.io/controller-runtime/pkg/client/mock_WithWatch.go
  test/mockery/mocks/porch/pkg/cache/crcache/meta/mock_MetadataStore.go
  test/mockery/mocks/porch/pkg/cache/dbcache/mock_dbSQLInterface.go
  test/mockery/mocks/porch/pkg/cache/types/mock_Cache.go
  test/mockery/mocks/porch/pkg/cache/types/mock_RepoPRChangeNotifier.go
  test/mockery/mocks/porch/pkg/engine/mock_CaDEngine.go
  test/mockery/mocks/porch/pkg/repository/mock_PackageRevision.go
  test/mockery/mocks/porch/pkg/repository/mock_PackageRevisionDraft.go
  test/mockery/mocks/porch/pkg/repository/mock_Repository.go
Labels: approved, lgtm
