Repository nephio-project/porch, pull requests merged in 2025-06, with the labels that each got.

#242 Evict failed pods from cache and trigger fresh pod creation.
  func/internal/podevaluator.go
  func/internal/podevaluator_podmanager_test.go
  test/e2e/e2e_test.go
Labels: enhancement, approved, lgtm, ok-to-test

#259 Added Service frontend to function evaluation pods to fix Istio integration issues
  deployments/porch/5-rbac.yaml
  func/internal/podevaluator.go
  func/internal/podevaluator_podcachemanager_test.go
  func/internal/podevaluator_podmanager_test.go
Labels: approved, lgtm

#268 Fix Watcher objects continually created, but not removed - fixes issue #943
  pkg/engine/watchermanager.go
  pkg/engine/watchermanager_test.go
Labels: approved, lgtm, needs-ok-to-test

#263 Make Porch's commit messages more human readable (fixes #936)
  pkg/externalrepo/git/git.go
  pkg/externalrepo/git/git_test.go
Labels: approved, lgtm

#269 Remove local prow jobs
  .github/workflows/sonar-ci-artifacts.yaml
  .github/workflows/sonarcloud.yml
  .prow.yaml
  Makefile
Labels: bug, approved, lgtm
