Repository nephio-project/porch, pull requests merged in 2025-04, with the labels that each got.

#219 Porch Code coverage
  pkg/cli/commands/commands.go
  pkg/cli/commands/commands_test.go
  pkg/cli/commands/repo/reg/command_test.go
  pkg/cli/commands/repo/reg/testdata/simple-oci-repository.yaml
  pkg/cli/commands/repo/repocmd_test.go
  pkg/cli/commands/rpkg/get/command_test.go
  pkg/cli/commands/rpkg/update/command_test.go
  pkg/cli/commands/util/factory_test.go
Labels: approved, lgtm

#174 Proposal- Porch Performance Testing Framework - Operation Flow with Prometheus
  sonar-project.properties
  test/performance/README.md
  test/performance/gitea-secret.yaml
  test/performance/logger.go
  test/performance/metrics.go
  test/performance/porch_metrics_test.go
  test/performance/prometheus_metrics.go
  test/performance/promql_queries.txt
  test/performance/types.go
Labels: approved, lgtm

#220 #888: Porch periodic background job is not doing anything
  pkg/cache/crcache/cache.go
  pkg/cache/crcache/repository.go
  pkg/registry/porch/background.go
Labels: approved, lgtm

#165 fix for #631 where slight differences seen in Kptfile upstream format…
  pkg/kpt/clone.go
  pkg/kpt/clone_test.go
Labels: approved, lgtm

#222 Porch Code Coverage
  pkg/task/generictaskhandler_test.go
  pkg/task/patchgen.go
  pkg/task/patchgen_test.go
Labels: approved, lgtm

#223 porchctl - Fix Update issue when the package has local changes
  pkg/cli/commands/rpkg/update/command.go
  test/e2e/cli/testdata/rpkg-update/config.yaml
Labels: bug, approved, lgtm

#225 Allow verbosity of logs to be set in Function Runner and Wrapper Server
  func/internal/executableevaluator.go
  func/internal/podevaluator.go
  func/internal/podevaluator_podmanager_test.go
  func/server/server.go
  func/wrapper-server/main.go
  func/wrapper-server/testdata/config-map.yaml
  func/wrapper-server/testdata/cron-job.yaml
  func/wrapper-server/testdata/deployment.yaml
  func/wrapper-server/testdata/replaced/config-map.yaml
  func/wrapper-server/testdata/replaced/cron-job.yaml
  func/wrapper-server/testdata/replaced/deployment.yaml
  func/wrapper-server/testdata/search_replace_test.sh
  func/wrapper-server/testdata/search_replace_test_fail.sh
  func/wrapper-server/wrapper_server_test.go
Labels: approved, lgtm, ok-to-test

#227 Iterative performance test as extension of E2E suite
  test/e2e/performance/README.md
  test/e2e/performance/config.yaml
  test/e2e/performance/iterative_test.go
  test/e2e/performance/iterative_types.go
  test/e2e/performance/performance_suite.go
  test/e2e/performance/prometheus.go
  test/e2e/performance/prometheus_in_docker.sh
  test/e2e/performance/utils.go
  test/e2e/suite.go
Labels: approved, lgtm

#228 Remove unnecessary remote interactions for `gitRepository.DeletePackageRevision`
  pkg/externalrepo/git/commit.go
  pkg/externalrepo/git/commit_test.go
  pkg/externalrepo/git/git.go
  pkg/externalrepo/git/git_test.go
  pkg/externalrepo/git/gogit.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: approved, lgtm

#231 Update performance test Prometheus config
  test/e2e/performance/config.yml
  test/e2e/performance/performance_suite.go
  test/e2e/performance/prometheus_in_docker.sh
  test/e2e/performance/rules.yml
Labels: approved, lgtm
